name: create_repo
on:
  workflow_dispatch:
    inputs:
      repo_prefix:
        description: 'set repo prefix'
        required: true
        default: 'inflearn'
        type: choice
        options:
          - inflearn
          - github-action
          - service
      repo_name:
        description: 'set repo name'
        required: true
        default: 'test'
        type: string
      set_template:
        description: 'set repo prefix'
        required: true
        default: 'action-test'
        type: choice
        options:
          - action-test
          - action-module

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: create repository (Use template)
        run: |
          gh repo create sangwondevops/${{ inputs.repo_prefix }}-${{ inputs.repo_name }} --public --template sangwondevops/${{ inputs.set_template }}
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  
  slack:
    runs-on: ubuntu-latest
    needs: [create_repo]
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Create repository",
              "attachments": [
                {
                  "pretext": "Create repo finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Create repo",
                      "short": true,
                      "value": "${{ inputs.repo_prefix }}-${{ inputs.repo_name }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TEST_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          
          