name: "branch deploy demo"
on:
  issue_comment:
    types: [created]
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  deploy-dev:
    if: |
      github.event.issue.pull_request && contains(github.event.comment.body, 'deploy dev')
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ github.event }}
          echo "======================="
          echo "${{ toJson(github.event) }}"
          echo "======================="
          echo ${{ github.event.comment.body }}
      - name: deploy dev
        run: |
          echo "Deploy dev"

  deploy-prod:
    if: |
      github.event.issue.pull_request && contains(github.event.comment.body, 'deploy prod')
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ github.event }}
          echo "======================="
          echo "${{ toJson(github.event) }}"
          echo "======================="
          echo ${{ github.event.comment.body }}
      - name: deploy prod
        run: |
          echo "Deploy prod"
