apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-a
  namespace: example-a-{{ .Values.environment }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      component: react-app
  template:
    metadata:
      labels:
        component: react-app
    spec:
      containers:
        - name: react-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
