apiVersion: v1
kind: Service
metadata:
  name: example-a
  namespace: example-a-{{ .Values.environment }}
spec:
  selector:
    component: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
#   type: ClusterIP
