name: issue_comment
on: issue_comment

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.issue.number }}
          echo "${{ toJson(github.event) }}"

  issue_commented:
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.issue.number }}
          echo "${{ toJson(github.event) }}"