name: issue_comment
on: 
  issue_comment:
    types: [opened]

jobs:
  pr_comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.issue.number }}
          echo "${{ toJson(github.event) }}"

  issue_comment:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.issue.number }}
          echo "${{ toJson(github.event) }}"