name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "job1 done" 
  
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: echo
        run: echo "job2 job done"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: exit 1
        run: |
          echo "job3 failed"
          exit 1
  
  job4:
    needs: [job3]
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "job4 job done"

