name: repository_dispatch
on:
  repository_dispatch:
    types: [test_result]

jobs:
  repository_dispatch:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.message }}




      