name: workflow_dispatch
on: workflow_dispatch

jobs:
  workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: step1 echo hello world
        run: echo Hello, world!
      - name: step2 echo github action
        run: |
          echo Hello, world!
          echo github action !

# name: workflow_dispatch
# on: 
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'set env'
#         required: true
#         default: 'develop'
#         type: choice
#         options: 
#           - develop
#           - prodution
#       name:
#         description: 'set name'
#         required: true
#         default: 'github-actions'
#       project:
#         description: 'set project'
#         required: false
#         default: 'test'
      

# jobs:
#   workflow_dispatch:
#     runs-on: ubuntu-latest
#     steps:
#       - name: step1 echo hello world
#         run: echo Hello, world!
#       - name: step2 echo github action
#         run: |
#           echo Hello, world!
#           echo github action !
#       - name: echo inputs
#         run: |
#           echo "NAME: ${{ inputs.name }}"
#           echo "ENVIRONMENT: ${{ inputs.environment }}"
#           echo "PROJECT: ${{ inputs.project }}"
      
