name: environment
on: workflow_dispatch

env:
  Greeting: github-action
  DAY_OF_WEEK: Monday

jobs:
  global_environment:
    runs-on: ubuntu-latest
    steps:
      - name: echo ENV 
        run: echo "$Greeting . Today is $DAY_OF_WEEK!"

  steps_environment:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello-World
      DAY_OF_WEEK: Sunday
    steps:
      - name: echo ENV 
        run: echo "$Greeting . Today is $DAY_OF_WEEK!"
      - name: echo ENV 
        run: echo "$Greeting . Today is $DAY_OF_WEEK!"
        env:
          Greeting: test
          DAY_OF_WEEK: Friday
           
###################################################################################################

  org_environment:
    runs-on: ubuntu-latest
    steps:
      - name: check environment
        run: |
          echo ${{ vars.ACTION_TEST }}
          
  repo_environment:
    runs-on: ubuntu-latest
    steps:
      - name: check environment
        run: |
          echo ${{ vars.ACTION_TEST }}
  
  develop_environment:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: check environment
        run: |
          echo ${{ vars.ACTION_TEST }}