name: job_summary
on:
  workflow_dispatch:

jobs:
  job_summary_1:
    runs-on: ubuntu-latest
    steps:
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY

  job_summary_2:
    runs-on: ubuntu-latest
    steps:
      - name: Generate list using Markdown
        run: |
          {
            echo "### :rocket: Workflow inputs"
            echo "| Arg                 | Value |"
            echo "| ------------------- | ----- |"
            echo "| Environment         | ${{ inputs.environment }} |"
            echo "| Skip Test           | ${{ inputs.skip_test }} |"
            echo "| Set Branch          | ${{ inputs.set_branch }} |"
          } >> $GITHUB_STEP_SUMMARY

