name: create_repo
on:
  workflow_dispatch:
    inputs:
      repo_prefix:
        description: 'set repo prefix'
        required: true
        default: 'inflearn'
        type: choice
        options:
          - inflearn
          - github-action
          - service
      repo_name:
        description: 'set repo name'
        required: true
        default: 'test'
        type: string
      use_template:
        description: 'set template'
        required: false
        type: boolean
      set_template:
        description: 'set repo prefix'
        required: true
        default: 'action-test'
        type: choice
        options:
          - action-test
          - action-module
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: echo use_template
        run: |
          echo ${{ inputs.use_template }}
      - name: create repository (Use template)
        if: ${{ inputs.use_template }} == 'true'
        run: |
          gh repo create sangwondevops/${{ inputs.repo_prefix }}-${{ inputs.repo_name }} --public --template sangwondevops/${{ inputs.set_template }}
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: create repository
        if: ${{ inputs.use_template }} == 'false'
        run: |
          gh repo create sangwondevops/${{ inputs.repo_prefix }}-${{ inputs.repo_name }} --public --add-readme
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

          
          