name: "branch deploy demo"
on:
  issue_comment:
    types: [created]
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  deploy-test:
    if: |
      github.event.issue.pull_request && contains(github.event.comment.body, 'test') 
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ github.event }}
          echo "======================="
          echo "${{ toJson(github.event) }}"
          echo "======================="
          echo ${{ github.event.comment.body }}
          ${{ steps.branch-deploy.outputs.ref }}
      - uses: github/branch-deploy@v5.2.2
        id: branch-deploy
        with:
          trigger: ".deploy"
      - name: check output
        run: |
          echo "${{ toJson(steps.branch-deploy.outputs) }}" 
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}
      - name: fake noop deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' }}
        run: |
          echo "I am doing a fake noop deploy"
      - name: fake regular deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        run: |
          echo "I am doing a fake regular deploy"

  deploy-hello:
    if: |
      github.event.issue.pull_request && contains(github.event.comment.body, 'hello') 
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ github.event }}
          echo "======================="
          echo "${{ toJson(github.event) }}"
          echo "======================="
          echo ${{ github.event.comment.body }}
          ${{ steps.branch-deploy.outputs.ref }}
      - uses: github/branch-deploy@v5.2.2
        id: branch-deploy
        with:
          trigger: ".check"
      - name: check output
        run: |
          echo "${{ toJson(steps.branch-deploy.outputs) }}" 
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-deploy.outputs.ref }}
      - name: fake noop deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' }}
        run: |
          echo "I am doing a fake noop deploy"
      - name: fake regular deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        run: |
          echo "I am doing a fake regular deploy"