name: repository_dispatch
on:
  repository_dispatch:
    types: [test]

jobs:
  check_payload:
    runs-on: ubuntu-latest
    steps:
      - name: check payload
        run: |
          echo ${{ github.event.client_payload.name }}
          echo ${{ github.event.client_payload.count }}